### ISSUE TITLE
Large output of craziness

### ISSUE THREAD

**Issue by sean-hill** [driftyco/ionic-service-deploy#18]
Hey there,

After Ionic Deploy successfully downloaded and extracted an update, it threw these errors in my console. It tried to load the Facebook SDK as a local file instead of over the network, and it didn't play nice with the StatusBar plugin. Just throwing this out there...

![Ionic Deploy Issues](https://www.dropbox.com/s/zfexg31a6dfbpw4/Screen%20Shot%202015-06-19%20at%208.18.27%20AM.png?dl=1)

**Comment by Ionitron** [comment]
Greetings @sean-hill!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
